#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────
# Orchestratia Agent diagnostic bundle.
#
# Captures everything needed to debug grant-setup failures on a target
# server: subprocess.run isolation tests, system info, sudoers config,
# recent daemon log, daemon version. Writes to a single file you can
# paste back or attach to a support thread.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/kumarimlab/orchestratia-agent/main/scripts/diag.sh | sudo bash
#
# Output:
#   /tmp/orchestratia-diag-<timestamp>.log
# ──────────────────────────────────────────────────────────────────────
set -u

TS=$(date -u +"%Y%m%d-%H%M%S")
OUT="/tmp/orchestratia-diag-${TS}.log"

# The daemon runs as a non-root user. Try to pick the right one for
# the subprocess tests so we exercise the same code path the daemon
# does. Fall back to $SUDO_USER if set, then $USER, then 'root'.
DAEMON_USER="${SUDO_USER:-${USER:-root}}"
if systemctl show orchestratia-agent -p User --value 2>/dev/null | grep -q .; then
    SU=$(systemctl show orchestratia-agent -p User --value 2>/dev/null)
    [ -n "$SU" ] && DAEMON_USER="$SU"
fi

# Helper — write to both stdout and the log file. Output to stdout is
# nice so the user sees progress; the file is the canonical copy.
say() { echo "$*" | tee -a "$OUT"; }
hdr() { say ""; say "=========================================================="; say "$*"; say "=========================================================="; }
run() { say "\$ $*"; { eval "$*" 2>&1 | tee -a "$OUT"; } || true; say ""; }

# Bootstrap log file
echo "Orchestratia Agent diagnostic — ${TS}" > "$OUT"
echo "Generated by scripts/diag.sh" >> "$OUT"
echo "" >> "$OUT"

hdr "ENVIRONMENT"
run "uname -a"
run "cat /etc/os-release | grep -E '^(NAME|VERSION|ID)='"
run "python3 --version"
run "which python3"
run "sudo --version | head -1"
run "id"
say "Daemon will be tested as user: $DAEMON_USER"

hdr "AGENT INSTALL"
run "ls -la /opt/orchestratia-venv/bin/orchestratia* 2>&1 | head -5"
run "/opt/orchestratia-venv/bin/orchestratia --version 2>&1 || echo 'orchestratia binary not found'"
run "systemctl is-active orchestratia-agent 2>&1"
run "systemctl show orchestratia-agent -p MainPID --value 2>&1"

hdr "SUDOERS CONFIG"
run "sudo cat /etc/sudoers.d/orchestratia-agent 2>&1 | head -30"
say ""
say "(Above should include 'NOPASSWD: /usr/bin/mkdir -p /home/orchestratia/.ssh')"

hdr "TARGET FILESYSTEM STATE"
run "id orchestratia 2>&1"
run "sudo ls -la /home/orchestratia/ 2>&1"
run "sudo ls -la /home/orchestratia/.ssh/ 2>&1 || true"

hdr "SUBPROCESS ISOLATION TESTS (as $DAEMON_USER)"
say "Reproducing the exact subprocess.run pattern the daemon uses."
say "Each test is independent — if Test 1 times out but Test 3 works,"
say "we have a Python subprocess + sudo interaction bug."
say ""

# Run python tests AS the daemon user (drops privileges).
sudo -u "$DAEMON_USER" python3 - 2>&1 <<'PY' | tee -a "$OUT"
import subprocess, os, time

def banner(n, label):
    print(f"--- Test {n}: {label} ---")

# Test 1: exactly what the agent does (capture_output + timeout)
banner(1, "subprocess.run([sudo,mkdir], capture_output=True, timeout=10)")
t = time.time()
try:
    r = subprocess.run(
        ["sudo", "-n", "mkdir", "-p", "/tmp/orc-diag-1"],
        capture_output=True, text=True, timeout=10,
    )
    print(f"  rc={r.returncode}  elapsed={time.time()-t:.2f}s")
    if r.stderr:
        print(f"  stderr: {r.stderr.strip()[:200]}")
except subprocess.TimeoutExpired as e:
    print(f"  TIMED OUT after {time.time()-t:.2f}s")
    print(f"  partial stderr: {(e.stderr or '')[:200]!r}")
print()

# Test 2: without capture_output (no internal pipe threads)
banner(2, "subprocess.run([sudo,mkdir], timeout=10)  (no capture)")
t = time.time()
try:
    r = subprocess.run(
        ["sudo", "-n", "mkdir", "-p", "/tmp/orc-diag-2"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=10,
    )
    print(f"  rc={r.returncode}  elapsed={time.time()-t:.2f}s")
except subprocess.TimeoutExpired:
    print(f"  TIMED OUT after {time.time()-t:.2f}s")
print()

# Test 3: os.system (totally different API path — uses /bin/sh)
banner(3, "os.system('sudo -n mkdir ... >/dev/null 2>&1')")
t = time.time()
rc = os.system("sudo -n mkdir -p /tmp/orc-diag-3 >/dev/null 2>&1")
print(f"  rc={rc >> 8}  elapsed={time.time()-t:.2f}s")
print()

# Test 4: Popen + wait() without timeout (no communicate() machinery)
banner(4, "Popen + wait() (no timeout, no communicate)")
t = time.time()
proc = subprocess.Popen(
    ["sudo", "-n", "mkdir", "-p", "/tmp/orc-diag-4"],
    stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
)
rc = proc.wait(timeout=15)
print(f"  rc={rc}  elapsed={time.time()-t:.2f}s")
print()

# Test 5: time sudo by itself, no Python wrapper at all
banner(5, "shell-level: time sudo -n true")
os.system("time sudo -n true 2>&1")
PY

hdr "RECENT DAEMON LOG"
run "sudo journalctl -u orchestratia-agent --since '5 min ago' --no-pager | tail -60"

hdr "DAEMON PROCESS DETAILS"
PID=$(systemctl show orchestratia-agent -p MainPID --value 2>/dev/null)
if [ -n "$PID" ] && [ "$PID" != "0" ]; then
    run "sudo cat /proc/$PID/status 2>&1 | head -20"
    run "sudo ls /proc/$PID/fd 2>&1 | wc -l"
    say "(FD count above — concerning if >100 on a fresh daemon)"
fi

hdr "DONE"
say ""
say "Output saved to: $OUT"
say ""
echo "=========================================================="
echo "  Share this file:"
echo "    cat $OUT"
echo "=========================================================="
